DECLARE
  P_MSG_ID VARCHAR2(200);
  P_REQUEST_ID VARCHAR2(200);
  P_DBG_MD VARCHAR2(200);
  P_SC_ID VARCHAR2(200);
  P_FUN_ID VARCHAR2(200);
  P_REQ_MODE VARCHAR2(200);
  P_CUST_LANG_PREF VARCHAR2(200);
  P_CIF VARCHAR2(200);
  P_USER_ID VARCHAR2(200);
  P_AGENT_ID VARCHAR2(200);
  P_STATUS_CODE VARCHAR2(200);
  P_STATUS_DESC VARCHAR2(200);
  P_SAMA_REQUEST_ID VARCHAR2(200);
BEGIN
  P_MSG_ID := NULL;
  P_REQUEST_ID := NULL;
  P_DBG_MD := NULL;
  P_SC_ID := NULL;
  P_FUN_ID := NULL;
  P_REQ_MODE := NULL;
  P_CUST_LANG_PREF := NULL;
  P_CIF := NULL;
  P_USER_ID := NULL;
  P_AGENT_ID := NULL;
  P_SAMA_REQUEST_ID := '20180327-1513-0040-0470-201803271513';

  MANAGE_REQUEST_HISTORY(
    P_MSG_ID => P_MSG_ID,
    P_REQUEST_ID => P_REQUEST_ID,
    P_DBG_MD => P_DBG_MD,
    P_SC_ID => P_SC_ID,
    P_FUN_ID => P_FUN_ID,
    P_REQ_MODE => P_REQ_MODE,
    P_CUST_LANG_PREF => P_CUST_LANG_PREF,
    P_CIF => P_CIF,
    P_USER_ID => P_USER_ID,
    P_AGENT_ID => P_AGENT_ID,
    P_STATUS_CODE => P_STATUS_CODE,
    P_STATUS_DESC => P_STATUS_DESC,
    P_SAMA_REQUEST_ID => P_SAMA_REQUEST_ID
  );
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_STATUS_CODE = ' || P_STATUS_CODE);
*/ 
  :P_STATUS_CODE := P_STATUS_CODE;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_STATUS_DESC = ' || P_STATUS_DESC);
*/ 
  :P_STATUS_DESC := P_STATUS_DESC;
--rollback; 
END;
