DECLARE
  P_MSG_ID VARCHAR2(200);
  P_REQUEST_ID VARCHAR2(200);
  P_DBG_MD VARCHAR2(200);
  P_SC_ID VARCHAR2(200);
  P_FUN_ID VARCHAR2(200);
  P_REQ_MODE VARCHAR2(200);
  P_CUST_LANG_PREF VARCHAR2(200);
  P_CIF VARCHAR2(200);
  P_USER_ID VARCHAR2(200);
  P_AGENT_ID VARCHAR2(200);
  P_STATUS_CODE VARCHAR2(200);
  P_STATUS_DESC VARCHAR2(200);
  P_SAMA_REQUEST_ID VARCHAR2(200);
  P_SAMA_REQUEST_TS VARCHAR2(200);
  P_REQUEST_SC_ID VARCHAR2(200);
  P_REQUEST_SC_IP_ADDRESS VARCHAR2(200);
  P_PARTNER_ID VARCHAR2(200);
  P_REQUEST_CHANNEL_ID VARCHAR2(200);
  P_REQUEST_SUB_CHANNEL_ID VARCHAR2(200);
  P_SRC_REQUEST_MODE VARCHAR2(200);
  P_CONFIDENTIALITY_FLAG VARCHAR2(200);
  P_CORRELATION_REFERENCE VARCHAR2(200);
  P_REQUEST_CLASSIFICATION VARCHAR2(200);
  P_PREVIOUS_HASH VARCHAR2(200);
  P_REQUESTER_ID VARCHAR2(200);
  P_REQUESTER_NAME VARCHAR2(200);
  P_REQUESTER_POSITION VARCHAR2(200);
  P_REQUESTER_REFERENCE_NUMBER VARCHAR2(200);
  P_REQUESTER_GEO_LOCATION VARCHAR2(200);
  P_REQUESTER_GEO_LOCATION_DESC VARCHAR2(200);
  P_PARTY_TYPE VARCHAR2(200);
  P_PARTY_ID VARCHAR2(200);
  P_PARTY_ID_TYPE VARCHAR2(200);
  P_PARTY_NAME VARCHAR2(200);
  P_PARTY_FIRST_NAME VARCHAR2(200);
  P_PARTY_SECOND_NAME VARCHAR2(200);
  P_PARTY_THIRD_NAME VARCHAR2(200);
  P_PARTY_LAST_NAME VARCHAR2(200);
  P_PARTY_NATIONALITY VARCHAR2(200);
  P_THIRD_PARTY_ID VARCHAR2(200);
  P_THIRD_PARTY_ID_TYPE VARCHAR2(200);
  P_THIRD_PARTY_NAME VARCHAR2(200);
  P_CUSTOMER_FIRST_NAME_AR VARCHAR2(200);
  P_CUSTOMER_SECOND_NAME_AR VARCHAR2(200);
  P_CUSTOMER_THIRD_NAME_AR VARCHAR2(200);
  P_CUSTOMER_LAST_NAME_AR VARCHAR2(200);
  P_CUSTOMER_FULL_NAME_AR VARCHAR2(200);
  P_CUSTOMER_FIRST_NAME_EN VARCHAR2(200);
  P_CUSTOMER_SECOND_NAME_EN VARCHAR2(200);
  P_CUSTOMER_THIRD_NAME_EN VARCHAR2(200);
  P_CUSTOMER_LAST_NAME_EN VARCHAR2(200);
  P_CUSTOMER_FULL_NAME_EN VARCHAR2(200);
  P_CUSTOMER_CIC VARCHAR2(200);
  P_ACCOUNT_NUMBER VARCHAR2(200);
  P_IBAN VARCHAR2(200);
  P_APPROVER_COMMENT VARCHAR2(200);
  P_TERMINATION_REASON VARCHAR2(200);
  P_REQUEST_MESSAGE CLOB;
  P_RESPONSE_MESSAGE CLOB;
  P_SAMA_REQUEST_TYPE VARCHAR2(200);
  P_STM_ID VARCHAR2(200);
  P_LAST_STATE VARCHAR2(200);
  P_SRN VARCHAR2(200);
  P_BPM_INSTANCE_ID VARCHAR2(200);
  P_FULFILLER_ID VARCHAR2(200);
  P_APPROVER_ID VARCHAR2(200);
  P_REQUEST_SUB_TYPE VARCHAR2(200);
  P_ACTIVITY VARCHAR2(200);
  P_AUDIT_TRAIL CLOB;
  P_BPM_DATA CLOB;
BEGIN
  P_MSG_ID := NULL;
  P_REQUEST_ID := '97c227cb-bb78-4200-b26e-8025fe04d0d9';
  P_DBG_MD := NULL;
  P_SC_ID := 'FI Portal';
  P_FUN_ID := 'C';
  P_REQ_MODE := NULL;
  P_CUST_LANG_PREF := NULL;
  P_CIF := NULL;
  P_USER_ID := NULL;
  P_AGENT_ID := NULL;
  P_SAMA_REQUEST_ID := '9898989';
  P_SAMA_REQUEST_TS := '2019-01-22T15:45:45';
  P_REQUEST_SC_ID := NULL;
  P_REQUEST_SC_IP_ADDRESS := 'testValue';
  P_PARTNER_ID := '10100';
  P_REQUEST_CHANNEL_ID := 'testValue';
  P_REQUEST_SUB_CHANNEL_ID := 'testValue';
  P_SRC_REQUEST_MODE := NULL;
  P_CONFIDENTIALITY_FLAG := NULL;
  P_CORRELATION_REFERENCE := 'testValue';
  P_REQUEST_CLASSIFICATION := 'testValue';
  P_PREVIOUS_HASH := 'testValue';
  P_REQUESTER_ID := NULL;
  P_REQUESTER_NAME := 'testValue';
  P_REQUESTER_POSITION := 'testValue';
  P_REQUESTER_REFERENCE_NUMBER := 'testValue';
  P_REQUESTER_GEO_LOCATION := 'testValue';
  P_REQUESTER_GEO_LOCATION_DESC := 'testValue';
  P_PARTY_TYPE := 'testValue';
  P_PARTY_ID := NULL;
  P_PARTY_ID_TYPE := 'testValue';
  P_PARTY_NAME := 'testValue';
  P_PARTY_FIRST_NAME := 'testValue';
  P_PARTY_SECOND_NAME := 'testValue';
  P_PARTY_THIRD_NAME := 'testValue';
  P_PARTY_LAST_NAME := 'testValue';
  P_PARTY_NATIONALITY := 'testValue';
  P_THIRD_PARTY_ID := NULL;
  P_THIRD_PARTY_ID_TYPE := 'testValue';
  P_THIRD_PARTY_NAME := 'testValue';
  P_CUSTOMER_FIRST_NAME_AR := 'testValue';
  P_CUSTOMER_SECOND_NAME_AR := 'testValue';
  P_CUSTOMER_THIRD_NAME_AR := 'testValue';
  P_CUSTOMER_LAST_NAME_AR := 'testValue';
  P_CUSTOMER_FULL_NAME_AR := 'testValue';
  P_CUSTOMER_FIRST_NAME_EN := 'testValue';
  P_CUSTOMER_SECOND_NAME_EN := 'testValue';
  P_CUSTOMER_THIRD_NAME_EN := 'testValue';
  P_CUSTOMER_LAST_NAME_EN := 'testValue';
  P_CUSTOMER_FULL_NAME_EN := 'testValue';
  P_CUSTOMER_CIC := 'testValue';
  P_ACCOUNT_NUMBER := 'testValue';
  P_IBAN := 'testValue';
  P_APPROVER_COMMENT := 'testValue';
  P_TERMINATION_REASON := 'testValue';
  P_REQUEST_MESSAGE := NULL;
  P_RESPONSE_MESSAGE := NULL;
  P_SAMA_REQUEST_TYPE := 'G';
  P_STM_ID := '97c227cb-bb78-4200-b26e-8025fe04d0d9';
  P_LAST_STATE := 'testValue';
  P_SRN := '20181022130300190256';
  P_BPM_INSTANCE_ID := NULL;
  P_FULFILLER_ID := NULL;
  P_APPROVER_ID := NULL;
  P_REQUEST_SUB_TYPE := 'testValue';
  P_ACTIVITY := 'testValue';
  P_AUDIT_TRAIL := NULL;
  P_BPM_DATA := NULL;

  MANAGE_SAMA_REQUEST(
    P_MSG_ID => P_MSG_ID,
    P_REQUEST_ID => P_REQUEST_ID,
    P_DBG_MD => P_DBG_MD,
    P_SC_ID => P_SC_ID,
    P_FUN_ID => P_FUN_ID,
    P_REQ_MODE => P_REQ_MODE,
    P_CUST_LANG_PREF => P_CUST_LANG_PREF,
    P_CIF => P_CIF,
    P_USER_ID => P_USER_ID,
    P_AGENT_ID => P_AGENT_ID,
    P_STATUS_CODE => P_STATUS_CODE,
    P_STATUS_DESC => P_STATUS_DESC,
    P_SAMA_REQUEST_ID => P_SAMA_REQUEST_ID,
    P_SAMA_REQUEST_TS => P_SAMA_REQUEST_TS,
    P_REQUEST_SC_ID => P_REQUEST_SC_ID,
    P_REQUEST_SC_IP_ADDRESS => P_REQUEST_SC_IP_ADDRESS,
    P_PARTNER_ID => P_PARTNER_ID,
    P_REQUEST_CHANNEL_ID => P_REQUEST_CHANNEL_ID,
    P_REQUEST_SUB_CHANNEL_ID => P_REQUEST_SUB_CHANNEL_ID,
    P_SRC_REQUEST_MODE => P_SRC_REQUEST_MODE,
    P_CONFIDENTIALITY_FLAG => P_CONFIDENTIALITY_FLAG,
    P_CORRELATION_REFERENCE => P_CORRELATION_REFERENCE,
    P_REQUEST_CLASSIFICATION => P_REQUEST_CLASSIFICATION,
    P_PREVIOUS_HASH => P_PREVIOUS_HASH,
    P_REQUESTER_ID => P_REQUESTER_ID,
    P_REQUESTER_NAME => P_REQUESTER_NAME,
    P_REQUESTER_POSITION => P_REQUESTER_POSITION,
    P_REQUESTER_REFERENCE_NUMBER => P_REQUESTER_REFERENCE_NUMBER,
    P_REQUESTER_GEO_LOCATION => P_REQUESTER_GEO_LOCATION,
    P_REQUESTER_GEO_LOCATION_DESC => P_REQUESTER_GEO_LOCATION_DESC,
    P_PARTY_TYPE => P_PARTY_TYPE,
    P_PARTY_ID => P_PARTY_ID,
    P_PARTY_ID_TYPE => P_PARTY_ID_TYPE,
    P_PARTY_NAME => P_PARTY_NAME,
    P_PARTY_FIRST_NAME => P_PARTY_FIRST_NAME,
    P_PARTY_SECOND_NAME => P_PARTY_SECOND_NAME,
    P_PARTY_THIRD_NAME => P_PARTY_THIRD_NAME,
    P_PARTY_LAST_NAME => P_PARTY_LAST_NAME,
    P_PARTY_NATIONALITY => P_PARTY_NATIONALITY,
    P_THIRD_PARTY_ID => P_THIRD_PARTY_ID,
    P_THIRD_PARTY_ID_TYPE => P_THIRD_PARTY_ID_TYPE,
    P_THIRD_PARTY_NAME => P_THIRD_PARTY_NAME,
    P_CUSTOMER_FIRST_NAME_AR => P_CUSTOMER_FIRST_NAME_AR,
    P_CUSTOMER_SECOND_NAME_AR => P_CUSTOMER_SECOND_NAME_AR,
    P_CUSTOMER_THIRD_NAME_AR => P_CUSTOMER_THIRD_NAME_AR,
    P_CUSTOMER_LAST_NAME_AR => P_CUSTOMER_LAST_NAME_AR,
    P_CUSTOMER_FULL_NAME_AR => P_CUSTOMER_FULL_NAME_AR,
    P_CUSTOMER_FIRST_NAME_EN => P_CUSTOMER_FIRST_NAME_EN,
    P_CUSTOMER_SECOND_NAME_EN => P_CUSTOMER_SECOND_NAME_EN,
    P_CUSTOMER_THIRD_NAME_EN => P_CUSTOMER_THIRD_NAME_EN,
    P_CUSTOMER_LAST_NAME_EN => P_CUSTOMER_LAST_NAME_EN,
    P_CUSTOMER_FULL_NAME_EN => P_CUSTOMER_FULL_NAME_EN,
    P_CUSTOMER_CIC => P_CUSTOMER_CIC,
    P_ACCOUNT_NUMBER => P_ACCOUNT_NUMBER,
    P_IBAN => P_IBAN,
    P_APPROVER_COMMENT => P_APPROVER_COMMENT,
    P_TERMINATION_REASON => P_TERMINATION_REASON,
    P_REQUEST_MESSAGE => P_REQUEST_MESSAGE,
    P_RESPONSE_MESSAGE => P_RESPONSE_MESSAGE,
    P_SAMA_REQUEST_TYPE => P_SAMA_REQUEST_TYPE,
    P_STM_ID => P_STM_ID,
    P_LAST_STATE => P_LAST_STATE,
    P_SRN => P_SRN,
    P_BPM_INSTANCE_ID => P_BPM_INSTANCE_ID,
    P_FULFILLER_ID => P_FULFILLER_ID,
    P_APPROVER_ID => P_APPROVER_ID,
    P_REQUEST_SUB_TYPE => P_REQUEST_SUB_TYPE,
    P_ACTIVITY => P_ACTIVITY,
    P_AUDIT_TRAIL => P_AUDIT_TRAIL,
    P_BPM_DATA => P_BPM_DATA
  );
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_STATUS_CODE = ' || P_STATUS_CODE);
*/ 
  :P_STATUS_CODE := P_STATUS_CODE;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_STATUS_DESC = ' || P_STATUS_DESC);
*/ 
  :P_STATUS_DESC := P_STATUS_DESC;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_STM_ID = ' || P_STM_ID);
*/ 
  :P_STM_ID := P_STM_ID;
--rollback; 
END;
