create or replace TRIGGER UPDATE_CE_SNOOZE
   AFTER UPDATE  ON CUSTOMERS_EMAILS FOR EACH ROW


DECLARE
   V_REAL_DUE TIMESTAMP(6);
   
   
BEGIN
   
IF ((:NEW.CE_SNOOZE_TO_DATE <> :OLD.CE_SNOOZE_TO_DATE  AND :NEW.CE_SNOOZE_TO_DATE IS NOT NULL) OR
    (:NEW.CE_BLOCK_TO_TIME <> :OLD.CE_BLOCK_TO_TIME  AND :NEW.CE_BLOCK_TO_TIME IS NOT NULL))THEN
    
    
    V_REAL_DUE := GET_CONTACT_DUE_TO_TIMESTAMP (P_SNOOZE_TIME      => :NEW.CE_SNOOZE_TO_DATE,
                                                P_BLOCK_TIME       => :NEW.CE_BLOCK_TO_TIME);
                                      
  
   FOR I IN (SELECT MN_RELATION_TYPE_CODE, MN_RELATION_VALUE, MN_DUE_TO_TIMESTAMP
             FROM MESSAGE_NOTIFICATIONS
             WHERE MN_NOTIFICATION_CHANNEL = 'EMAIL'
             AND MN_RELATION_TYPE_CODE = :NEW.CE_RELATION_TYPE_CODE
             AND MN_RELATION_VALUE = :NEW.CE_RELATION_VALUE
             AND MN_CONTACT = :NEW.CE_EMAIL
             AND (MN_DUE_TO_TIMESTAMP = NULL
              OR MN_DUE_TO_TIMESTAMP < V_REAL_DUE )) LOOP
              
  
      UPDATE MESSAGE_NOTIFICATIONS
      SET MN_DUE_TO_TIMESTAMP = V_REAL_DUE
      WHERE MN_NOTIFICATION_CHANNEL = 'EMAIL'
      AND MN_CONTACT = :NEW.CE_EMAIL
      AND MN_RELATION_TYPE_CODE = I.MN_RELATION_TYPE_CODE
      AND MN_RELATION_VALUE = I.MN_RELATION_VALUE;
      
  END LOOP;
  
  
    FOR Y IN (SELECT MNB_RELATION_TYPE_CODE, MNB_RELATION_VALUE, MNB_DUE_TO_TIMESTAMP
             FROM MESSAGE_NOTIFICATIONS_BULK
             WHERE MNB_NOTIFICATION_CHANNEL = 'EMAIL'
             AND MNB_RELATION_TYPE_CODE = :NEW.CE_RELATION_TYPE_CODE
             AND MNB_RELATION_VALUE = :NEW.CE_RELATION_VALUE
             AND MNB_CONTACT = :NEW.CE_EMAIL
             AND (MNB_DUE_TO_TIMESTAMP = NULL
              OR MNB_DUE_TO_TIMESTAMP < V_REAL_DUE )) LOOP
              
  
      UPDATE MESSAGE_NOTIFICATIONS_BULK
      SET MNB_DUE_TO_TIMESTAMP = V_REAL_DUE
      WHERE MNB_NOTIFICATION_CHANNEL = 'EMAIL'
      AND MNB_CONTACT = :NEW.CE_EMAIL
      AND MNB_RELATION_TYPE_CODE = Y.MNB_RELATION_TYPE_CODE
      AND MNB_RELATION_VALUE = Y.MNB_RELATION_VALUE;
      
  END LOOP;
  
END IF;
 
      
END;