

  CREATE TABLE MERCHANT 
   (	M_MERCHANT_ID number NOT NULL, --generated by db sequence and returned in case function create 
	    M_AR_DESCRIPTION VARCHAR2(200),
		M_EN_DESCRIPTION VARCHAR2(200),
		M_ALSMPL_ID  VARCHAR2(50),
    M_STATUS VARCHAR2(30) --LOV [Active / Suspended/ Deleted]
		
   ) ;
   
   
    CREATE TABLE MERCHANT_TERMINAL 
	   ( MT_TERMINAL_ID number NOT NULL, --generated by db sequence and returned in case function create 
   	MT_MERCHANT_ID number NOT NULL, 
	    MT_AR_DESCRIPTION VARCHAR2(200),
		MT_EN_DESCRIPTION VARCHAR2(200),
        MT_STATUS VARCHAR2(30) ,--LOV [Active / Suspended/ Deleted]
        MT_ADDRESS VARCHAR2(500),
        MT_TRANSACTION_LIMIT VARCHAR2(100),
        MT_DAILY_LIMIT VARCHAR2(100),
        MT_CONTACT VARCHAR2(100),
		MT_SWALLET_NUMBER VARCHAR2(12)
   ) ;

