DECLARE
  P_MSG_ID VARCHAR2(200);
  P_REQUEST_ID VARCHAR2(200);
  P_DBG_MD VARCHAR2(200);
  P_SC_ID VARCHAR2(200);
  P_FUN_ID VARCHAR2(200);
  P_REQ_MODE VARCHAR2(200);
  P_CUST_LANG_PREF VARCHAR2(200);
  P_CIF VARCHAR2(200);
  P_USER_ID VARCHAR2(200);
  P_AGENT_ID VARCHAR2(200);
  P_STATUS_CODE VARCHAR2(200);
  P_STATUS_DESC VARCHAR2(200);
  P_SAMA_REQUEST_ID VARCHAR2(200);
  P_SRN VARCHAR2(200);
  P_BPM_INSTANCE_ID VARCHAR2(200);
  P_CUSTOMER_CIC VARCHAR2(200);
  P_PARTY_TYPE VARCHAR2(200);
  P_PARTY_ID_TYPE VARCHAR2(200);
  P_PARTY_ID VARCHAR2(200);
  P_PARTY_NAME VARCHAR2(200);
  P_ACCOUNT_NUMBER VARCHAR2(200);
  P_REQUEST_TS VARCHAR2(200);
  P_STATE VARCHAR2(200);
  P_ACTIVITY VARCHAR2(200);
  P_REQUEST_MESSAGE CLOB;
  P_RESPONSE_MESSAGE CLOB;
  P_AUDIT_TRAIL CLOB;
  P_BPM_DATA CLOB;
BEGIN
  P_MSG_ID := NULL;
  P_REQUEST_ID := NULL;
  P_DBG_MD := NULL;
  P_SC_ID := NULL;
  P_FUN_ID := NULL;
  P_REQ_MODE := NULL;
  P_CUST_LANG_PREF := NULL;
  P_CIF := NULL;
  P_USER_ID := NULL;
  P_AGENT_ID := NULL;
  P_SAMA_REQUEST_ID := '20180327-1513-0040-0470-201803271513';
  P_SRN := NULL;
  P_BPM_INSTANCE_ID := NULL;

  GET_SAMA_REQUEST_DETAILS(
    P_MSG_ID => P_MSG_ID,
    P_REQUEST_ID => P_REQUEST_ID,
    P_DBG_MD => P_DBG_MD,
    P_SC_ID => P_SC_ID,
    P_FUN_ID => P_FUN_ID,
    P_REQ_MODE => P_REQ_MODE,
    P_CUST_LANG_PREF => P_CUST_LANG_PREF,
    P_CIF => P_CIF,
    P_USER_ID => P_USER_ID,
    P_AGENT_ID => P_AGENT_ID,
    P_STATUS_CODE => P_STATUS_CODE,
    P_STATUS_DESC => P_STATUS_DESC,
    P_SAMA_REQUEST_ID => P_SAMA_REQUEST_ID,
    P_SRN => P_SRN,
    P_BPM_INSTANCE_ID => P_BPM_INSTANCE_ID,
    P_CUSTOMER_CIC => P_CUSTOMER_CIC,
    P_PARTY_TYPE => P_PARTY_TYPE,
    P_PARTY_ID_TYPE => P_PARTY_ID_TYPE,
    P_PARTY_ID => P_PARTY_ID,
    P_PARTY_NAME => P_PARTY_NAME,
    P_ACCOUNT_NUMBER => P_ACCOUNT_NUMBER,
    P_REQUEST_TS => P_REQUEST_TS,
    P_STATE => P_STATE,
    P_ACTIVITY => P_ACTIVITY,
    P_REQUEST_MESSAGE => P_REQUEST_MESSAGE,
    P_RESPONSE_MESSAGE => P_RESPONSE_MESSAGE,
    P_AUDIT_TRAIL => P_AUDIT_TRAIL,
    P_BPM_DATA => P_BPM_DATA
  );
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_STATUS_CODE = ' || P_STATUS_CODE);
*/ 
  :P_STATUS_CODE := P_STATUS_CODE;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_STATUS_DESC = ' || P_STATUS_DESC);
*/ 
  :P_STATUS_DESC := P_STATUS_DESC;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_SAMA_REQUEST_ID = ' || P_SAMA_REQUEST_ID);
*/ 
  :P_SAMA_REQUEST_ID := P_SAMA_REQUEST_ID;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_SRN = ' || P_SRN);
*/ 
  :P_SRN := P_SRN;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_BPM_INSTANCE_ID = ' || P_BPM_INSTANCE_ID);
*/ 
  :P_BPM_INSTANCE_ID := P_BPM_INSTANCE_ID;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_CUSTOMER_CIC = ' || P_CUSTOMER_CIC);
*/ 
  :P_CUSTOMER_CIC := P_CUSTOMER_CIC;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_PARTY_TYPE = ' || P_PARTY_TYPE);
*/ 
  :P_PARTY_TYPE := P_PARTY_TYPE;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_PARTY_ID_TYPE = ' || P_PARTY_ID_TYPE);
*/ 
  :P_PARTY_ID_TYPE := P_PARTY_ID_TYPE;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_PARTY_ID = ' || P_PARTY_ID);
*/ 
  :P_PARTY_ID := P_PARTY_ID;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_PARTY_NAME = ' || P_PARTY_NAME);
*/ 
  :P_PARTY_NAME := P_PARTY_NAME;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_ACCOUNT_NUMBER = ' || P_ACCOUNT_NUMBER);
*/ 
  :P_ACCOUNT_NUMBER := P_ACCOUNT_NUMBER;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_REQUEST_TS = ' || P_REQUEST_TS);
*/ 
  :P_REQUEST_TS := P_REQUEST_TS;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_STATE = ' || P_STATE);
*/ 
  :P_STATE := P_STATE;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_ACTIVITY = ' || P_ACTIVITY);
*/ 
  :P_ACTIVITY := P_ACTIVITY;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_REQUEST_MESSAGE = ' || P_REQUEST_MESSAGE);
*/ 
  :P_REQUEST_MESSAGE := P_REQUEST_MESSAGE;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_RESPONSE_MESSAGE = ' || P_RESPONSE_MESSAGE);
*/ 
  :P_RESPONSE_MESSAGE := P_RESPONSE_MESSAGE;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_AUDIT_TRAIL = ' || P_AUDIT_TRAIL);
*/ 
  :P_AUDIT_TRAIL := P_AUDIT_TRAIL;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_BPM_DATA = ' || P_BPM_DATA);
*/ 
  :P_BPM_DATA := P_BPM_DATA;
--rollback; 
END;
