DECLARE
  P_MSG_ID VARCHAR2(200);
  P_SC_ID VARCHAR2(200);
  P_FUN_ID VARCHAR2(200);
  P_REQ_MODE VARCHAR2(200);
  P_CUST_LANG_PREF VARCHAR2(200);
  P_USER_ID VARCHAR2(200);
  P_CLIENT_DATE VARCHAR2(200);
  P_VERSION VARCHAR2(200);
  P_STATUS_CODE VARCHAR2(200);
  P_STATUS_DESC VARCHAR2(200);
  P_USER_ROLE VARCHAR2(200);
  P_ORDER_BY VARCHAR2(200);
  P_ORDER_DIRECTION VARCHAR2(200);
  P_MAX_RECORDS VARCHAR2(200);
  P_OFFSET VARCHAR2(200);
  P_MATCHED_RECORDS VARCHAR2(200);
  P_SENT_RECORDS VARCHAR2(200);
  P_STATUS_LIST CLOB;
BEGIN
  P_MSG_ID := NULL;
  P_SC_ID := NULL;
  P_FUN_ID := NULL;
  P_REQ_MODE := NULL;
  P_CUST_LANG_PREF := NULL;
  P_USER_ID := NULL;
  P_CLIENT_DATE := NULL;
  P_VERSION := NULL;
  P_USER_ROLE := 'Approver';
  P_ORDER_BY := 'ACTION';
  P_ORDER_DIRECTION := 'DESC';
  P_MAX_RECORDS := NULL;
  P_OFFSET := NULL;

  GET_STATUS_LIST(
    P_MSG_ID => P_MSG_ID,
    P_SC_ID => P_SC_ID,
    P_FUN_ID => P_FUN_ID,
    P_REQ_MODE => P_REQ_MODE,
    P_CUST_LANG_PREF => P_CUST_LANG_PREF,
    P_USER_ID => P_USER_ID,
    P_CLIENT_DATE => P_CLIENT_DATE,
    P_VERSION => P_VERSION,
    P_STATUS_CODE => P_STATUS_CODE,
    P_STATUS_DESC => P_STATUS_DESC,
    P_USER_ROLE => P_USER_ROLE,
    P_ORDER_BY => P_ORDER_BY,
    P_ORDER_DIRECTION => P_ORDER_DIRECTION,
    P_MAX_RECORDS => P_MAX_RECORDS,
    P_OFFSET => P_OFFSET,
    P_MATCHED_RECORDS => P_MATCHED_RECORDS,
    P_SENT_RECORDS => P_SENT_RECORDS,
    P_STATUS_LIST => P_STATUS_LIST
  );
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_STATUS_CODE = ' || P_STATUS_CODE);
*/ 
  :P_STATUS_CODE := P_STATUS_CODE;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_STATUS_DESC = ' || P_STATUS_DESC);
*/ 
  :P_STATUS_DESC := P_STATUS_DESC;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_MATCHED_RECORDS = ' || P_MATCHED_RECORDS);
*/ 
  :P_MATCHED_RECORDS := P_MATCHED_RECORDS;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_SENT_RECORDS = ' || P_SENT_RECORDS);
*/ 
  :P_SENT_RECORDS := P_SENT_RECORDS;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_STATUS_LIST = ' || P_STATUS_LIST);
*/ 
  :P_STATUS_LIST := P_STATUS_LIST;
--rollback; 
END;
