DECLARE
  P_MSG_ID VARCHAR2(200);
  P_SC_ID VARCHAR2(200);
  P_FUN_ID VARCHAR2(200);
  P_REQ_MODE VARCHAR2(200);
  P_CUST_LANG_PREF VARCHAR2(200);
  P_USER_ID VARCHAR2(200);
  P_CLIENT_DATE VARCHAR2(200);
  P_VERSION VARCHAR2(200);
  P_STATUS_CODE VARCHAR2(200);
  P_STATUS_DESC VARCHAR2(200);
  P_REQUEST_STM_ID_LIST VARCHAR2(200);
  P_ASSIGNED_TO_USER VARCHAR2(200);
BEGIN
  P_MSG_ID := NULL;
  P_SC_ID := NULL;
  P_FUN_ID := NULL;
  P_REQ_MODE := NULL;
  P_CUST_LANG_PREF := NULL;
  P_USER_ID := NULL;
  P_CLIENT_DATE := NULL;
  P_VERSION := NULL;
  P_REQUEST_STM_ID_LIST := '1702,1627';
  P_ASSIGNED_TO_USER := '2';

  ASSIGN_REQUEST(
    P_MSG_ID => P_MSG_ID,
    P_SC_ID => P_SC_ID,
    P_FUN_ID => P_FUN_ID,
    P_REQ_MODE => P_REQ_MODE,
    P_CUST_LANG_PREF => P_CUST_LANG_PREF,
    P_USER_ID => P_USER_ID,
    P_CLIENT_DATE => P_CLIENT_DATE,
    P_VERSION => P_VERSION,
    P_STATUS_CODE => P_STATUS_CODE,
    P_STATUS_DESC => P_STATUS_DESC,
    P_REQUEST_STM_ID_LIST => P_REQUEST_STM_ID_LIST,
    P_ASSIGNED_TO_USER => P_ASSIGNED_TO_USER
  );
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_STATUS_CODE = ' || P_STATUS_CODE);
*/ 
  :P_STATUS_CODE := P_STATUS_CODE;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_STATUS_DESC = ' || P_STATUS_DESC);
*/ 
  :P_STATUS_DESC := P_STATUS_DESC;
--rollback; 
END;
