
ALTER TABLE REQUEST_HISTORY ADD RH_ASSIGNED_TO VARCHAR2(15);
ALTER TABLE REQUEST_HISTORY ADD RH_ASSIGNEMENT_TS TIMESTAMP;


COMMENT ON COLUMN "REQUEST_HISTORY"."RH_ASSIGNED_TO" IS 'Assigned To';
COMMENT ON COLUMN "REQUEST_HISTORY"."RH_ASSIGNEMENT_TS" IS 'Assignment Timestamp';